print("Sub Conjuntos\n")
print("Ejemplo 1:")
ca = {1, 2, 3, 4, 5}
cb = {2, 5}
print("Conjunto A: ",ca)
print("Conjunto B: ",cb)
print("\nAveriguar si es subconjunto por medio del método issubset()")
print("A es subconjunto de B: ",ca.issubset(cb))
print("B es subconjunto de A: ",cb.issubset(ca))
print("\nOperadores de subconjuntos")
print("\nAveriguar si es subconjunto por medio del operador inclusivo <=")
print("A es subconjunto de B: ",ca <= cb)
print("B es subconjunto de A: ",cb <= ca)
print("\nAveriguar si es subconjunto por medio del operador estricto <")
print("A es subconjunto de B: ",ca < cb)
print("B es subconjunto de A: ",cb < ca)
print("\nEjemplo 2:")
ca = {1, 2, 3, 4, 5}
cb = {1, 2, 3, 4, 5}
print("Conjunto A: ",ca)
print("Conjunto B: ",cb)
print("\nAveriguar si es subconjunto por medio del método issubset()")
print("A es subconjunto de B: ",ca.issubset(cb))
print("B es subconjunto de A: ",cb.issubset(ca))
print("\nOperadores de subconjuntos")
print("\nAveriguar si es subconjunto por medio del operador inclusivo <=")
print("A es subconjunto de B: ",ca <= cb)
print("B es subconjunto de A: ",cb <= ca)
print("\nAveriguar si es subconjunto por medio del operador estricto <")
print("A es subconjunto de B: ",ca < cb)
print("B es subconjunto de A: ",cb < ca)
