print("Super Conjuntos\n")
print("Ejemplo 1:")
ca = {1, 2, 3, 4, 5}
cb = {2, 5}
print("Conjunto A: ",ca)
print("Conjunto B: ",cb)
print("\nAveriguar si es superconjunto por medio del método issuperset()")
print("A es superconjunto de B: ",ca.issuperset(cb))
print("B es superconjunto de A: ",cb.issuperset(ca))
print("\nOperadores de superconjuntos")
print("\nAveriguar si es superconjunto por medio del operador inclusivo >=")
print("A es superconjunto de B: ",ca >= cb)
print("B es superconjunto de A: ",cb >= ca)
print("\nAveriguar si es superconjunto por medio del operador estricto >")
print("A es superconjunto de B: ",ca > cb)
print("B es superconjunto de A: ",cb > ca)
print("\nEjemplo 2:")
ca = {1, 2, 3, 4, 5}
cb = {1, 2, 3, 4, 0}
print("Conjunto A: ",ca)
print("Conjunto B: ",cb)
print("\nAveriguar si es superconjunto por medio del método issuperset()")
print("A es superconjunto de B: ",ca.issuperset(cb))
print("B es superconjunto de A: ",cb.issuperset(ca))
print("\nOperadores de superconjuntos")
print("\nAveriguar si es superconjunto por medio del operador inclusivo >=")
print("A es superconjunto de B: ",ca >= cb)
print("B es superconjunto de A: ",cb >= ca)
print("\nAveriguar si es superconjunto por medio del operador estricto >")
print("A es superconjunto de B: ",ca > cb)
print("B es superconjunto de A: ",cb > ca)
